name: telco360
version: "1.0.0"
profile: telco360

model-paths: ["models"]
test-paths: ["tests"]

models:
  telco360:
    staging:
      +materialized: view    # vue : nettoyage léger, toujours à jour
    intermediate:
      +materialized: table   # logique métier (jointures), écrasé par config incrémentale si besoin
    marts:
      +materialized: table   # tables finales, prêtes pour l'app / les notebooks
